apiVersion: v1
kind: Deployment
metadata:
       name: mydeploy
spec:
   replicas: 3
   selector:
      app: dev
   template:
     metadata:
       labels:
         app: dev
       name: mynginx23
       namespace: default
    spec:
      containers:
         image: nginx
         imagePullPolicy: Always
         name: mynginx2
